version: "3.8"

services:
  backend:
    build: ./backend
    container_name: xstudio_backend
    restart: always
    ports:
      - "8001:8001"
    networks:
      - xstudio_net
    command: uvicorn main:app --host 0.0.0.0 --port 8001

  frontend:
    build: ./frontend
    container_name: xstudio_frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - BACKEND_ORIGIN=http://backend:8001
    depends_on:
      - backend
    networks:
      - xstudio_net
    command: npm run start -- -p 3001 -H 0.0.0.0

networks:
  xstudio_net:
    driver: bridge
